export const facilityDefinitions = {
  Market: {
    label: 'Market',
    cost: 300,
    icon: '/icons/market.png',
    description: 'Shopping place',
    benefits: 'Economic activation, job growth, and increased tax revenue',
    drawbacks: 'Increased traffic congestion and noise pollution',
    impacts: {
      populationPercent: 0.03,
      trafficPercent: 0.05,
      crimePercent: 0.02,
      housingSatisfactionPercent: 0.01,
      unemploymentPercent: -0.02,
      housingSupplyPercent: 0.005,
      airQualityPercent: -0.03,
      inflationPercent: 0.002,
    },
  },
  School: {
    label: 'School',
    cost: 500,
    icon: '/icons/school.png',
    description: 'Education center',
    benefits: 'Improved education outcomes and population growth',
    drawbacks: 'Potential overcrowding and additional public spending',
    impacts: {
      populationPercent: 0.05,
      trafficPercent: -0.02,
      crimePercent: -0.05,
      housingSatisfactionPercent: 0.04,
      unemploymentPercent: -0.03,
      housingSupplyPercent: 0.002,
      airQualityPercent: 0.02,
      inflationPercent: 0.001,
    },
  },
  CommunityCentre: {
    label: 'Community Centre',
    cost: 400,
    icon: '/icons/communitycentre.png',
    description: 'Community activities and services',
    benefits: 'Increased housing satisfaction and stronger community connections',
    drawbacks: 'Ongoing facility maintenance costs',
    impacts: {
      populationPercent: 0.02,
      trafficPercent: -0.01,
      crimePercent: -0.03,
      housingSatisfactionPercent: 0.07,
      unemploymentPercent: -0.01,
      housingSupplyPercent: 0.001,
      airQualityPercent: 0.04,
      inflationPercent: 0.001,
    },
  },
  Hospital: {
    label: 'Hospital',
    cost: 800,
    icon: '/icons/hospital.png',
    description: 'Healthcare facility',
    benefits: 'Improved healthcare access and public safety',
    drawbacks: 'Higher operating costs and local traffic demand',
    impacts: {
      populationPercent: 0.03,
      trafficPercent: -0.10,
      crimePercent: -0.02,
      housingSatisfactionPercent: 0.03,
      unemploymentPercent: -0.01,
      housingSupplyPercent: 0,
      airQualityPercent: 0.05,
      inflationPercent: 0.001,
    },
  },
  PoliceStation: {
    label: 'Police Station',
    cost: 600,
    icon: '/icons/policestation.png',
    description: 'Public safety facility',
    benefits: 'Reduced crime and increased resident safety',
    drawbacks: 'Staffing and operating cost requirements',
    impacts: {
      populationPercent: 0.01,
      trafficPercent: -0.15,
      crimePercent: -0.20,
      housingSatisfactionPercent: 0.05,
      unemploymentPercent: 0,
      housingSupplyPercent: 0,
      airQualityPercent: 0.01,
      inflationPercent: 0,
    },
  },
  NonProfitHousing: {
    label: 'Non-Market Housing',
    cost: 700,
    icon: '/icons/nonprofithousing.png',
    description: 'Affordable non-profit housing',
    benefits: 'Improved housing stability and support for lower-income residents',
    drawbacks: 'Additional land, funding, and service requirements',
    impacts: {
      populationPercent: 0.08,
      trafficPercent: 0.02,
      crimePercent: 0.01,
      housingSatisfactionPercent: 0.10,
      unemploymentPercent: -0.05,
      housingSupplyPercent: 0.02,
      airQualityPercent: -0.05,
      inflationPercent: 0.002,
    },
  },
  Daycare: {
    label: 'Government-Funded Daycare',
    cost: 100,
    icon: '/icons/daycare.png',
    description: 'Publicly funded child care',
    benefits: 'Support for young families and workforce participation',
    drawbacks: 'Operating costs and limited facility capacity',
    impacts: {
      populationPercent: 0.04,
      trafficPercent: 0,
      crimePercent: 0,
      housingSatisfactionPercent: 0.03,
      unemploymentPercent: -0.01,
      housingSupplyPercent: 0,
      airQualityPercent: 0,
      inflationPercent: 0.001,
    },
  },
  SeniorCentre: {
    label: 'Senior Centre',
    cost: 200,
    icon: '/icons/seniorcentre.png',
    description: 'Services and programs for seniors',
    benefits: 'Improved senior well-being and stronger community connections',
    drawbacks: 'Operating costs and ongoing resource requirements',
    impacts: {
      populationPercent: 0.02,
      trafficPercent: 0,
      crimePercent: -0.01,
      housingSatisfactionPercent: 0.06,
      unemploymentPercent: 0,
      housingSupplyPercent: 0,
      airQualityPercent: 0.01,
      inflationPercent: 0,
    },
  },
};

export const facilityOptions = Object.entries(facilityDefinitions).map(
  ([name, definition]) => ({
    name,
    label: definition.label,
    cost: definition.cost,
    icon: definition.icon,
    popup: `${definition.label}: ${definition.description}`,
  })
);

export const facilityImpactData = Object.entries(facilityDefinitions).map(
  ([facility, definition]) => ({
    facility,
    populationChange: definition.impacts.populationPercent * 100,
    trafficChange: definition.impacts.trafficPercent * 100,
    crimeChange: definition.impacts.crimePercent * 100,
    housingSatisfaction: definition.impacts.housingSatisfactionPercent * 100,
    unemploymentChange: definition.impacts.unemploymentPercent * 100,
    housingSupplyRate: definition.impacts.housingSupplyPercent * 100,
    airQualityChange: definition.impacts.airQualityPercent * 100,
    inflationRate: definition.impacts.inflationPercent * 100,
  })
);
